name: scfvtools_env
channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - python=3.10
  - pip
  - biopython>=1.85
  - pandas
  - numpy
  - bottleneck
  - openpyxl
  - anarci
  - hmmer
  - pip:
      - colorama==0.4.6
      - exceptiongroup==1.3.1
